#!/bin/bash
OUTPREFIX="/var/calculate/server-data/samba/public/music/OUTPUT"
ENCODER="/usr/bin/lame -b 192"
find . -name "*.ogg" | while read NAME
do
    CURDIR=`pwd`
    FILE=`basename "$NAME" .ogg`
    DIR=`dirname "$NAME"`
    SONGTITLE=` ogginfo "$NAME" | grep TITLE=  | awk -F = -e '{ print $2 }'`
    SONGDATE=`  ogginfo "$NAME" | grep DATE=   | awk -F = -e '{ print $2 }'`
    SONGARTIST=`ogginfo "$NAME" | grep ARTIST= | awk -F = -e '{ print $2 }'`
    SONGALBUM=` ogginfo "$NAME" | grep ALBUM=  | awk -F = -e '{ print $2 }'`
    mkdir -p "$OUTPREFIX/$SONGARTIST/$SONGDATE - $SONGALBUM"
    cd "$DIR"
    oggdec -Q -o - "$FILE.ogg" | $ENCODER  - "$OUTPREFIX/$SONGARTIST/$SONGDATE - $SONGALBUM/$FILE.mp3"
    id3tag -2 --song="$SONGTITLE" --artist="$SONGARTIST" --album="$SONGALBUM" --year="$SONGDATE" \
        "$OUTPREFIX/$SONGARTIST/$SONGDATE - $SONGALBUM/$FILE.mp3"
    cd "$CURDIR"
done